version: '3'

services:
  docker-mysql:
    image: mysql
    command:  --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3306 || exit 1"]
      interval: 1m30s
      timeout: 60s
      retries: 6

  flyway-service:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://docker-mysql:3306/test?verifyServerCertificate=false&useSSL=true -schemas=test -user=root -password=P@ssw0rd migrate
    volumes:
     - "./sql:/flyway/sql"
    depends_on:
     - docker-mysql
